### ISSUE TITLE
where can I find GeoJSON support?

### ISSUE THREAD

**Issue by bartekupartek** [hikeratlas/basemap#23]
This project is so great! Can't wait to adjust it to extract cycleways in my region hoverer I'm trying to run any export `./export/export ../planet-latest.osm.pbf ztrails` and it looks like lua can't find the global GeoJSON function, where can I find it?

```
ztrails.lua:63: attempt to call a nil value (global 'GeoJSON')'  `...tek/Downloads/hikeratlas/basemap/export/ztrails.lua:63: attempt to call a nil value (global 'GeoJSON')
```

**Comment by cldellow** [comment]
Hey! Be warned you might hit some rough edges. This is just a side project I hack on from time to time, but I'll happily take feedback and try to smooth out the rough edges over time.

The `GeoJSON` function is currently only available in my fork of tilemaker, on this branch: https://github.com/cldellow/tilemaker/tree/geojson-build-2

**Comment by bartekupartek** [comment]
It worked smoothly, thanks a ton! I just encountered two issues and opened tiny PRs: https://github.com/hikeratlas/basemap/pull/24 & https://github.com/cldellow/mapt/pull/10. Additionally, I needed to overcome some unrelated Lua quirks and build Tilemaker from source.

**Comment by bartekupartek** [comment]
actually I have now many separate pmtiles files, is there any way to merge them so I could load them as a single source on maplibre-gl?

**Comment by cldellow** [comment]
You should be able to use `bun mapt build --single` to get a single file, I think: https://github.com/cldellow/mapt?tab=readme-ov-file#--single

**Comment by bartekupartek** [comment]
with some tweaks for Lua > 5.2 it worked fine too, thx

**Comment by bartekupartek** [comment]
I run `bun mapt serve` and in index it listed my `*.pmfiles` however this files can't be resolved on the map, should II do some hack to serve ie `localhost:8081/buildings.pmtiles:1` etc?

**Comment by cldellow** [comment]
Hm, what does not resolved mean? A 404?

Can you share your operating environment details?

What is the `:1` you mention -- I think the file should not have that suffix.

I'm travelling for the week, so won't be able to offer much assistance in the near term, unfortunately.

**Comment by bartekupartek** [comment]
oh that was my bad, I'm testing it remotely on Arch host (due to Lua issues) from my MacBook and it turned out that source url for tiles is: `pmtiles://http://localhost:8081/${pmtiles}.pmtiles`; where I needed to change it to actual host IP from localhost, now this maps are wonderful, thanks again and happy travelling :)
